CREATE TABLE readings (id TEXT PRIMARY KEY, photo BLOB, lat REAL, lng REAL, value REAL, timestamp TEXT, synced INTEGER, tenant TEXT NOT NULL DEFAULT 'default', encrypted_blob TEXT, sync_status TEXT NOT NULL DEFAULT 'pending', sync_attempts INTEGER NOT NULL DEFAULT 0, dedupe_id TEXT, site_id INTEGER, device_id INTEGER, equipment_id INTEGER, calibration_id INTEGER, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE sites (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, technician_email TEXT, status TEXT NOT NULL DEFAULT 'active', tenant TEXT NOT NULL DEFAULT 'default', row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE sync_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', status TEXT NOT NULL, error_message TEXT, created_at TEXT NOT NULL, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE encryption_keys (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', derived_key TEXT NOT NULL, salt TEXT NOT NULL, device_fingerprint TEXT NOT NULL, created_at TEXT NOT NULL, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE devices (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', user_agent TEXT, technician_email TEXT, status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE outliers (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', reading_id INTEGER NOT NULL, resolved_by TEXT, resolved_at TEXT, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE sync_thresholds (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', action TEXT NOT NULL, threshold INTEGER NOT NULL, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE passphrases (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', hash TEXT NOT NULL, salt TEXT NOT NULL, created_at TEXT NOT NULL, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE daily_aggregates (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', date TEXT NOT NULL, avg_value REAL, min_value REAL, max_value REAL, count INTEGER NOT NULL, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE connectivity_zones (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', name TEXT NOT NULL, polygon_geojson TEXT, technician_email TEXT, status TEXT NOT NULL DEFAULT 'active', row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE reading_historys (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', reading_id INTEGER NOT NULL, changed_field TEXT NOT NULL, old_value TEXT, new_value TEXT, changed_by TEXT, changed_at TEXT NOT NULL, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE site_visits (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', site_id INTEGER NOT NULL, purpose TEXT, notes TEXT, technician_email TEXT, status TEXT NOT NULL DEFAULT 'scheduled', visited_at TEXT, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE equipments (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', serial_number TEXT NOT NULL, type TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE calibration_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', equipment_id INTEGER NOT NULL, calibrated_by TEXT, calibrated_at TEXT NOT NULL, notes TEXT, status TEXT NOT NULL DEFAULT 'valid', row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', recipient_email TEXT NOT NULL, type TEXT NOT NULL, content TEXT, related_entity_type TEXT, related_entity_id INTEGER, read_at TEXT, created_at TEXT NOT NULL, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE sync_policys (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', name TEXT NOT NULL, description TEXT, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE audit_trails (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', entity_type TEXT NOT NULL, entity_id INTEGER NOT NULL, action TEXT NOT NULL, performed_by TEXT, metadata TEXT, created_at TEXT NOT NULL, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE maintenance_schedules (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL DEFAULT 'default', equipment_id INTEGER NOT NULL, type TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'scheduled', notes TEXT, technician_email TEXT, scheduled_at TEXT NOT NULL, completed_at TEXT, row_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE jobs (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant TEXT NOT NULL, kind TEXT NOT NULL, payload TEXT, status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0, max_attempts INTEGER NOT NULL DEFAULT 3, run_at TEXT NOT NULL, last_error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS readings_tenant_idx ON readings (tenant);
CREATE INDEX IF NOT EXISTS readings_dedupe_idx ON readings (dedupe_id);
CREATE INDEX IF NOT EXISTS sites_tenant_idx ON sites (tenant);
CREATE INDEX IF NOT EXISTS sync_logs_tenant_idx ON sync_logs (tenant);
CREATE INDEX IF NOT EXISTS encryption_keys_tenant_idx ON encryption_keys (tenant);
CREATE INDEX IF NOT EXISTS devices_tenant_idx ON devices (tenant);
CREATE INDEX IF NOT EXISTS outliers_tenant_idx ON outliers (tenant);
CREATE INDEX IF NOT EXISTS sync_thresholds_tenant_idx ON sync_thresholds (tenant);
CREATE INDEX IF NOT EXISTS passphrases_tenant_idx ON passphrases (tenant);
CREATE INDEX IF NOT EXISTS daily_aggregates_tenant_idx ON daily_aggregates (tenant);
CREATE INDEX IF NOT EXISTS connectivity_zones_tenant_idx ON connectivity_zones (tenant);
CREATE INDEX IF NOT EXISTS reading_historys_tenant_idx ON reading_historys (tenant);
CREATE INDEX IF NOT EXISTS site_visits_tenant_idx ON site_visits (tenant);
CREATE INDEX IF NOT EXISTS equipments_tenant_idx ON equipments (tenant);
CREATE INDEX IF NOT EXISTS calibration_logs_tenant_idx ON calibration_logs (tenant);
CREATE INDEX IF NOT EXISTS notifications_tenant_idx ON notifications (tenant);
CREATE INDEX IF NOT EXISTS sync_policys_tenant_idx ON sync_policys (tenant);
CREATE INDEX IF NOT EXISTS audit_trails_tenant_idx ON audit_trails (tenant);
CREATE INDEX IF NOT EXISTS maintenance_schedules_tenant_idx ON maintenance_schedules (tenant);
CREATE INDEX IF NOT EXISTS jobs_tenant_status_idx ON jobs (tenant, status);
