-- GENERATED optimistic concurrency: the counter every write bumps.
ALTER TABLE readings ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE sync_logs ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE encryption_keys ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE erasure_policys ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE anomalys ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE grid_cells ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE technicians ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE sites ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE reading_types ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE sync_policys ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE devices ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE permissions ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE audit_logs ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE regions ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE maintenance_schedules ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE photo_blobs ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE sync_sessions ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1;
SELECT 1;
