// GENERATED from the manifest. Do not edit.
import type { Route } from "./lib/http";
import { limited } from "./handlers/ratelimit";
import { auditLog, login, logout, me, revokeSession, sessionsList, signup, userInvite, usersList, userSetRole } from "./handlers/auth";
import { jobCancel, jobRequeue, jobsList } from "./handlers/jobs";
import { search } from "./handlers/search";
import { uploadCreate, uploadDelete, uploadGet, uploadList } from "./handlers/uploads";
import { pendingReadings, syncStatusSummary, gridStatistics, siteAggregates, technicianPerformance, failedSyncs, erasureCandidates, readingAgeDistribution, readingTypeDistribution, siteAnomalyRate, technicianAnomalyRate, readingValueTrend, complianceReport, listReadings, listReadingsStats, getReading, createReading, createReadingBulk, updateReading, deleteReading, deleteReadingRestore } from "./handlers/reading";
import { detectAnomalies, listAnomalys, listAnomalysStats, getAnomaly, createAnomaly, createAnomalyBulk, updateAnomaly, deleteAnomaly, deleteAnomalyRestore } from "./handlers/anomaly";
import { listSync_logs, listSync_logsStats, getSync_log, createSync_log, createSync_logBulk, updateSync_log } from "./handlers/sync_log";
import { listEncryption_keys, listEncryption_keysStats, getEncryption_key, createEncryption_key, createEncryption_keyBulk, updateEncryption_key, deleteEncryption_key, deleteEncryption_keyRestore } from "./handlers/encryption_key";
import { listErasure_policys, listErasure_policysStats, getErasure_policy, createErasure_policy, createErasure_policyBulk, updateErasure_policy, deleteErasure_policy, deleteErasure_policyRestore } from "./handlers/erasure_policy";
import { listGrid_cells, listGrid_cellsStats, getGrid_cell, createGrid_cell, createGrid_cellBulk, updateGrid_cell, deleteGrid_cell, deleteGrid_cellRestore } from "./handlers/grid_cell";
import { listTechnicians, listTechniciansStats, getTechnician, createTechnician, createTechnicianBulk, updateTechnician, deleteTechnician, deleteTechnicianRestore } from "./handlers/technician";
import { listSites, listSitesStats, getSite, createSite, createSiteBulk, updateSite, deleteSite, deleteSiteRestore } from "./handlers/site";
import { listReading_types, listReading_typesStats, getReading_type, createReading_type, createReading_typeBulk, updateReading_type, deleteReading_type, deleteReading_typeRestore } from "./handlers/reading_type";
import { listSync_policys, listSync_policysStats, getSync_policy, createSync_policy, createSync_policyBulk, updateSync_policy, deleteSync_policy, deleteSync_policyRestore } from "./handlers/sync_policy";
import { listDevices, listDevicesStats, getDevice, createDevice, createDeviceBulk, updateDevice, deleteDevice, deleteDeviceRestore } from "./handlers/device";
import { listPermissions, listPermissionsStats, getPermission, createPermission, createPermissionBulk, updatePermission, deletePermission, deletePermissionRestore } from "./handlers/permission";
import { listAudit_logs, listAudit_logsStats, getAudit_log, createAudit_log, createAudit_logBulk, updateAudit_log } from "./handlers/audit_log";
import { listRegions, listRegionsStats, getRegion, createRegion, createRegionBulk, updateRegion, deleteRegion, deleteRegionRestore } from "./handlers/region";
import { listMaintenance_schedules, listMaintenance_schedulesStats, getMaintenance_schedule, createMaintenance_schedule, createMaintenance_scheduleBulk, updateMaintenance_schedule, deleteMaintenance_schedule, deleteMaintenance_scheduleRestore } from "./handlers/maintenance_schedule";
import { listPhoto_blobs, listPhoto_blobsStats, getPhoto_blob, createPhoto_blob, createPhoto_blobBulk, updatePhoto_blob, deletePhoto_blob, deletePhoto_blobRestore } from "./handlers/photo_blob";
import { listSync_sessions, listSync_sessionsStats, getSync_session, createSync_session, createSync_sessionBulk, updateSync_session, deleteSync_session, deleteSync_sessionRestore } from "./handlers/sync_session";

export const routes: Route[] = [
  { method: "POST", path: "/api/auth/signup", handler: limited(signup, "auth") },
  { method: "POST", path: "/api/auth/login", handler: limited(login, "auth") },
  { method: "POST", path: "/api/auth/logout", handler: limited(logout, "write") },
  { method: "GET", path: "/api/auth/me", handler: limited(me, "read") },
  { method: "GET", path: "/api/users", handler: limited(usersList, "read") },
  { method: "POST", path: "/api/users/invite", handler: limited(userInvite, "auth") },
  { method: "POST", path: "/api/users/:id/role", handler: limited(userSetRole, "write") },
  { method: "GET", path: "/api/audit", handler: limited(auditLog, "read") },
  { method: "GET", path: "/api/jobs", handler: limited(jobsList, "read") },
  { method: "POST", path: "/api/jobs/:id/cancel", handler: limited(jobCancel, "write") },
  { method: "POST", path: "/api/jobs/:id/requeue", handler: limited(jobRequeue, "write") },
  { method: "GET", path: "/api/search", handler: limited(search, "read") },
  { method: "POST", path: "/api/uploads", handler: limited(uploadCreate, "write") },
  { method: "GET", path: "/api/uploads", handler: limited(uploadList, "read") },
  { method: "GET", path: "/api/uploads/:id", handler: limited(uploadGet, "read") },
  { method: "DELETE", path: "/api/uploads/:id", handler: limited(uploadDelete, "write") },
  { method: "GET", path: "/api/sessions", handler: limited(sessionsList, "read") },
  { method: "DELETE", path: "/api/sessions/:id", handler: limited(revokeSession, "write") },
  { method: "GET", path: "/api/readings/stats", handler: limited(listReadingsStats, "read") },
  { method: "POST", path: "/api/readings/bulk", handler: limited(createReadingBulk, "write") },
  { method: "GET", path: "/api/sync_logs/stats", handler: limited(listSync_logsStats, "read") },
  { method: "POST", path: "/api/sync_logs/bulk", handler: limited(createSync_logBulk, "write") },
  { method: "GET", path: "/api/encryption_keys/stats", handler: limited(listEncryption_keysStats, "read") },
  { method: "POST", path: "/api/encryption_keys/bulk", handler: limited(createEncryption_keyBulk, "write") },
  { method: "GET", path: "/api/erasure_policys/stats", handler: limited(listErasure_policysStats, "read") },
  { method: "POST", path: "/api/erasure_policys/bulk", handler: limited(createErasure_policyBulk, "write") },
  { method: "GET", path: "/api/anomalys/stats", handler: limited(listAnomalysStats, "read") },
  { method: "POST", path: "/api/anomalys/bulk", handler: limited(createAnomalyBulk, "write") },
  { method: "GET", path: "/api/grid_cells/stats", handler: limited(listGrid_cellsStats, "read") },
  { method: "POST", path: "/api/grid_cells/bulk", handler: limited(createGrid_cellBulk, "write") },
  { method: "GET", path: "/api/technicians/stats", handler: limited(listTechniciansStats, "read") },
  { method: "POST", path: "/api/technicians/bulk", handler: limited(createTechnicianBulk, "write") },
  { method: "GET", path: "/api/sites/stats", handler: limited(listSitesStats, "read") },
  { method: "POST", path: "/api/sites/bulk", handler: limited(createSiteBulk, "write") },
  { method: "GET", path: "/api/reading_types/stats", handler: limited(listReading_typesStats, "read") },
  { method: "POST", path: "/api/reading_types/bulk", handler: limited(createReading_typeBulk, "write") },
  { method: "GET", path: "/api/sync_policys/stats", handler: limited(listSync_policysStats, "read") },
  { method: "POST", path: "/api/sync_policys/bulk", handler: limited(createSync_policyBulk, "write") },
  { method: "GET", path: "/api/devices/stats", handler: limited(listDevicesStats, "read") },
  { method: "POST", path: "/api/devices/bulk", handler: limited(createDeviceBulk, "write") },
  { method: "GET", path: "/api/permissions/stats", handler: limited(listPermissionsStats, "read") },
  { method: "POST", path: "/api/permissions/bulk", handler: limited(createPermissionBulk, "write") },
  { method: "GET", path: "/api/audit_logs/stats", handler: limited(listAudit_logsStats, "read") },
  { method: "POST", path: "/api/audit_logs/bulk", handler: limited(createAudit_logBulk, "write") },
  { method: "GET", path: "/api/regions/stats", handler: limited(listRegionsStats, "read") },
  { method: "POST", path: "/api/regions/bulk", handler: limited(createRegionBulk, "write") },
  { method: "GET", path: "/api/maintenance_schedules/stats", handler: limited(listMaintenance_schedulesStats, "read") },
  { method: "POST", path: "/api/maintenance_schedules/bulk", handler: limited(createMaintenance_scheduleBulk, "write") },
  { method: "GET", path: "/api/photo_blobs/stats", handler: limited(listPhoto_blobsStats, "read") },
  { method: "POST", path: "/api/photo_blobs/bulk", handler: limited(createPhoto_blobBulk, "write") },
  { method: "GET", path: "/api/sync_sessions/stats", handler: limited(listSync_sessionsStats, "read") },
  { method: "POST", path: "/api/sync_sessions/bulk", handler: limited(createSync_sessionBulk, "write") },
  { method: "GET", path: "/api/readings/pending", handler: limited(pendingReadings, "read") },
  { method: "GET", path: "/api/readings/sync-status", handler: limited(syncStatusSummary, "read") },
  { method: "GET", path: "/api/anomalies", handler: limited(detectAnomalies, "read") },
  { method: "GET", path: "/api/readings/grid-stats", handler: limited(gridStatistics, "read") },
  { method: "GET", path: "/api/readings/site-aggregates", handler: limited(siteAggregates, "read") },
  { method: "GET", path: "/api/readings/technician-performance", handler: limited(technicianPerformance, "read") },
  { method: "GET", path: "/api/sync/failed", handler: limited(failedSyncs, "read") },
  { method: "GET", path: "/api/readings/erasure-candidates", handler: limited(erasureCandidates, "read") },
  { method: "GET", path: "/api/readings/age-distribution", handler: limited(readingAgeDistribution, "read") },
  { method: "GET", path: "/api/readings/type-distribution", handler: limited(readingTypeDistribution, "read") },
  { method: "GET", path: "/api/readings/site-anomaly-rate", handler: limited(siteAnomalyRate, "read") },
  { method: "GET", path: "/api/readings/technician-anomaly-rate", handler: limited(technicianAnomalyRate, "read") },
  { method: "GET", path: "/api/readings/value-trend", handler: limited(readingValueTrend, "read") },
  { method: "GET", path: "/api/readings/compliance-report", handler: limited(complianceReport, "read") },
  { method: "GET", path: "/api/readings", handler: limited(listReadings, "read") },
  { method: "GET", path: "/api/readings/:id", handler: limited(getReading, "read") },
  { method: "POST", path: "/api/readings", handler: limited(createReading, "write") },
  { method: "PATCH", path: "/api/readings/:id", handler: limited(updateReading, "write") },
  { method: "DELETE", path: "/api/readings/:id", handler: limited(deleteReading, "write") },
  { method: "POST", path: "/api/readings/:id/restore", handler: limited(deleteReadingRestore, "write") },
  { method: "GET", path: "/api/sync_logs", handler: limited(listSync_logs, "read") },
  { method: "GET", path: "/api/sync_logs/:id", handler: limited(getSync_log, "read") },
  { method: "POST", path: "/api/sync_logs", handler: limited(createSync_log, "write") },
  { method: "PATCH", path: "/api/sync_logs/:id", handler: limited(updateSync_log, "write") },
  { method: "GET", path: "/api/encryption_keys", handler: limited(listEncryption_keys, "read") },
  { method: "GET", path: "/api/encryption_keys/:id", handler: limited(getEncryption_key, "read") },
  { method: "POST", path: "/api/encryption_keys", handler: limited(createEncryption_key, "write") },
  { method: "PATCH", path: "/api/encryption_keys/:id", handler: limited(updateEncryption_key, "write") },
  { method: "DELETE", path: "/api/encryption_keys/:id", handler: limited(deleteEncryption_key, "write") },
  { method: "POST", path: "/api/encryption_keys/:id/restore", handler: limited(deleteEncryption_keyRestore, "write") },
  { method: "GET", path: "/api/erasure_policys", handler: limited(listErasure_policys, "read") },
  { method: "GET", path: "/api/erasure_policys/:id", handler: limited(getErasure_policy, "read") },
  { method: "POST", path: "/api/erasure_policys", handler: limited(createErasure_policy, "write") },
  { method: "PATCH", path: "/api/erasure_policys/:id", handler: limited(updateErasure_policy, "write") },
  { method: "DELETE", path: "/api/erasure_policys/:id", handler: limited(deleteErasure_policy, "write") },
  { method: "POST", path: "/api/erasure_policys/:id/restore", handler: limited(deleteErasure_policyRestore, "write") },
  { method: "GET", path: "/api/anomalys", handler: limited(listAnomalys, "read") },
  { method: "GET", path: "/api/anomalys/:id", handler: limited(getAnomaly, "read") },
  { method: "POST", path: "/api/anomalys", handler: limited(createAnomaly, "write") },
  { method: "PATCH", path: "/api/anomalys/:id", handler: limited(updateAnomaly, "write") },
  { method: "DELETE", path: "/api/anomalys/:id", handler: limited(deleteAnomaly, "write") },
  { method: "POST", path: "/api/anomalys/:id/restore", handler: limited(deleteAnomalyRestore, "write") },
  { method: "GET", path: "/api/grid_cells", handler: limited(listGrid_cells, "read") },
  { method: "GET", path: "/api/grid_cells/:id", handler: limited(getGrid_cell, "read") },
  { method: "POST", path: "/api/grid_cells", handler: limited(createGrid_cell, "write") },
  { method: "PATCH", path: "/api/grid_cells/:id", handler: limited(updateGrid_cell, "write") },
  { method: "DELETE", path: "/api/grid_cells/:id", handler: limited(deleteGrid_cell, "write") },
  { method: "POST", path: "/api/grid_cells/:id/restore", handler: limited(deleteGrid_cellRestore, "write") },
  { method: "GET", path: "/api/technicians", handler: limited(listTechnicians, "read") },
  { method: "GET", path: "/api/technicians/:id", handler: limited(getTechnician, "read") },
  { method: "POST", path: "/api/technicians", handler: limited(createTechnician, "write") },
  { method: "PATCH", path: "/api/technicians/:id", handler: limited(updateTechnician, "write") },
  { method: "DELETE", path: "/api/technicians/:id", handler: limited(deleteTechnician, "write") },
  { method: "POST", path: "/api/technicians/:id/restore", handler: limited(deleteTechnicianRestore, "write") },
  { method: "GET", path: "/api/sites", handler: limited(listSites, "read") },
  { method: "GET", path: "/api/sites/:id", handler: limited(getSite, "read") },
  { method: "POST", path: "/api/sites", handler: limited(createSite, "write") },
  { method: "PATCH", path: "/api/sites/:id", handler: limited(updateSite, "write") },
  { method: "DELETE", path: "/api/sites/:id", handler: limited(deleteSite, "write") },
  { method: "POST", path: "/api/sites/:id/restore", handler: limited(deleteSiteRestore, "write") },
  { method: "GET", path: "/api/reading_types", handler: limited(listReading_types, "read") },
  { method: "GET", path: "/api/reading_types/:id", handler: limited(getReading_type, "read") },
  { method: "POST", path: "/api/reading_types", handler: limited(createReading_type, "write") },
  { method: "PATCH", path: "/api/reading_types/:id", handler: limited(updateReading_type, "write") },
  { method: "DELETE", path: "/api/reading_types/:id", handler: limited(deleteReading_type, "write") },
  { method: "POST", path: "/api/reading_types/:id/restore", handler: limited(deleteReading_typeRestore, "write") },
  { method: "GET", path: "/api/sync_policys", handler: limited(listSync_policys, "read") },
  { method: "GET", path: "/api/sync_policys/:id", handler: limited(getSync_policy, "read") },
  { method: "POST", path: "/api/sync_policys", handler: limited(createSync_policy, "write") },
  { method: "PATCH", path: "/api/sync_policys/:id", handler: limited(updateSync_policy, "write") },
  { method: "DELETE", path: "/api/sync_policys/:id", handler: limited(deleteSync_policy, "write") },
  { method: "POST", path: "/api/sync_policys/:id/restore", handler: limited(deleteSync_policyRestore, "write") },
  { method: "GET", path: "/api/devices", handler: limited(listDevices, "read") },
  { method: "GET", path: "/api/devices/:id", handler: limited(getDevice, "read") },
  { method: "POST", path: "/api/devices", handler: limited(createDevice, "write") },
  { method: "PATCH", path: "/api/devices/:id", handler: limited(updateDevice, "write") },
  { method: "DELETE", path: "/api/devices/:id", handler: limited(deleteDevice, "write") },
  { method: "POST", path: "/api/devices/:id/restore", handler: limited(deleteDeviceRestore, "write") },
  { method: "GET", path: "/api/permissions", handler: limited(listPermissions, "read") },
  { method: "GET", path: "/api/permissions/:id", handler: limited(getPermission, "read") },
  { method: "POST", path: "/api/permissions", handler: limited(createPermission, "write") },
  { method: "PATCH", path: "/api/permissions/:id", handler: limited(updatePermission, "write") },
  { method: "DELETE", path: "/api/permissions/:id", handler: limited(deletePermission, "write") },
  { method: "POST", path: "/api/permissions/:id/restore", handler: limited(deletePermissionRestore, "write") },
  { method: "GET", path: "/api/audit_logs", handler: limited(listAudit_logs, "read") },
  { method: "GET", path: "/api/audit_logs/:id", handler: limited(getAudit_log, "read") },
  { method: "POST", path: "/api/audit_logs", handler: limited(createAudit_log, "write") },
  { method: "PATCH", path: "/api/audit_logs/:id", handler: limited(updateAudit_log, "write") },
  { method: "GET", path: "/api/regions", handler: limited(listRegions, "read") },
  { method: "GET", path: "/api/regions/:id", handler: limited(getRegion, "read") },
  { method: "POST", path: "/api/regions", handler: limited(createRegion, "write") },
  { method: "PATCH", path: "/api/regions/:id", handler: limited(updateRegion, "write") },
  { method: "DELETE", path: "/api/regions/:id", handler: limited(deleteRegion, "write") },
  { method: "POST", path: "/api/regions/:id/restore", handler: limited(deleteRegionRestore, "write") },
  { method: "GET", path: "/api/maintenance_schedules", handler: limited(listMaintenance_schedules, "read") },
  { method: "GET", path: "/api/maintenance_schedules/:id", handler: limited(getMaintenance_schedule, "read") },
  { method: "POST", path: "/api/maintenance_schedules", handler: limited(createMaintenance_schedule, "write") },
  { method: "PATCH", path: "/api/maintenance_schedules/:id", handler: limited(updateMaintenance_schedule, "write") },
  { method: "DELETE", path: "/api/maintenance_schedules/:id", handler: limited(deleteMaintenance_schedule, "write") },
  { method: "POST", path: "/api/maintenance_schedules/:id/restore", handler: limited(deleteMaintenance_scheduleRestore, "write") },
  { method: "GET", path: "/api/photo_blobs", handler: limited(listPhoto_blobs, "read") },
  { method: "GET", path: "/api/photo_blobs/:id", handler: limited(getPhoto_blob, "read") },
  { method: "POST", path: "/api/photo_blobs", handler: limited(createPhoto_blob, "write") },
  { method: "PATCH", path: "/api/photo_blobs/:id", handler: limited(updatePhoto_blob, "write") },
  { method: "DELETE", path: "/api/photo_blobs/:id", handler: limited(deletePhoto_blob, "write") },
  { method: "POST", path: "/api/photo_blobs/:id/restore", handler: limited(deletePhoto_blobRestore, "write") },
  { method: "GET", path: "/api/sync_sessions", handler: limited(listSync_sessions, "read") },
  { method: "GET", path: "/api/sync_sessions/:id", handler: limited(getSync_session, "read") },
  { method: "POST", path: "/api/sync_sessions", handler: limited(createSync_session, "write") },
  { method: "PATCH", path: "/api/sync_sessions/:id", handler: limited(updateSync_session, "write") },
  { method: "DELETE", path: "/api/sync_sessions/:id", handler: limited(deleteSync_session, "write") },
  { method: "POST", path: "/api/sync_sessions/:id/restore", handler: limited(deleteSync_sessionRestore, "write") },
];
