// GENERATED from the manifest. Do not edit.
import type { Route } from "./lib/http";
import { limited } from "./handlers/ratelimit";
import { auditLog, login, logout, me, revokeSession, sessionsList, signup, userInvite, usersList, userSetRole } from "./handlers/auth";
import { jobCancel, jobRequeue, jobsList } from "./handlers/jobs";
import { search } from "./handlers/search";
import { uploadCreate, uploadDelete, uploadGet, uploadList } from "./handlers/uploads";
import { listOutliers, syncStatusHeatmap, siteReadingTrend, pendingSyncReadings, failedSyncThresholdReadings, dedupeCheck, listReadings, listReadingsStats, getReading, createReading, createReadingBulk, updateReading, deleteReading, deleteReadingRestore } from "./handlers/reading";
import { siteSyncStats, listSites, listSitesStats, getSite, createSite, createSiteBulk, updateSite, deleteSite, deleteSiteRestore } from "./handlers/site";
import { dailyAggregates, listDaily_aggregates, listDaily_aggregatesStats, getDaily_aggregate, createDaily_aggregate, createDaily_aggregateBulk, updateDaily_aggregate, deleteDaily_aggregate, deleteDaily_aggregateRestore } from "./handlers/daily_aggregate";
import { lowSyncZones, listConnectivity_zones, listConnectivity_zonesStats, getConnectivity_zone, createConnectivity_zone, createConnectivity_zoneBulk, updateConnectivity_zone, deleteConnectivity_zone, deleteConnectivity_zoneRestore } from "./handlers/connectivity_zone";
import { siteEquipmentStatus, warrantyExpiry, listEquipments, listEquipmentsStats, getEquipment, createEquipment, createEquipmentBulk, updateEquipment, deleteEquipment, deleteEquipmentRestore } from "./handlers/equipment";
import { unresolvedOutliers, listOutliers2, listOutliers2Stats, getOutlier, createOutlier, createOutlierBulk, updateOutlier, deleteOutlier, deleteOutlierRestore } from "./handlers/outlier";
import { upcomingVisits, listSite_visits, listSite_visitsStats, getSite_visit, createSite_visit, createSite_visitBulk, updateSite_visit, deleteSite_visit, deleteSite_visitRestore } from "./handlers/site_visit";
import { overdueCalibrations, listCalibration_logs, listCalibration_logsStats, getCalibration_log, createCalibration_log, createCalibration_logBulk, updateCalibration_log } from "./handlers/calibration_log";
import { lowBatteryDevices, listDevices, listDevicesStats, getDevice, createDevice, createDeviceBulk, updateDevice, deleteDevice, deleteDeviceRestore } from "./handlers/device";
import { overdueMaintenance, listMaintenance_schedules, listMaintenance_schedulesStats, getMaintenance_schedule, createMaintenance_schedule, createMaintenance_scheduleBulk, updateMaintenance_schedule, deleteMaintenance_schedule, deleteMaintenance_scheduleRestore } from "./handlers/maintenance_schedule";
import { listSync_logs, listSync_logsStats, getSync_log, createSync_log, createSync_logBulk, updateSync_log } from "./handlers/sync_log";
import { listEncryption_keys, listEncryption_keysStats, getEncryption_key, createEncryption_key, createEncryption_keyBulk, updateEncryption_key, deleteEncryption_key, deleteEncryption_keyRestore } from "./handlers/encryption_key";
import { listSync_thresholds, listSync_thresholdsStats, getSync_threshold, createSync_threshold, createSync_thresholdBulk, updateSync_threshold, deleteSync_threshold, deleteSync_thresholdRestore } from "./handlers/sync_threshold";
import { listPassphrases, listPassphrasesStats, getPassphrase, createPassphrase, createPassphraseBulk, updatePassphrase, deletePassphrase, deletePassphraseRestore } from "./handlers/passphrase";
import { listReading_historys, listReading_historysStats, getReading_history, createReading_history, createReading_historyBulk, updateReading_history } from "./handlers/reading_history";
import { listNotifications, listNotificationsStats, getNotification, createNotification, createNotificationBulk, updateNotification, deleteNotification, deleteNotificationRestore } from "./handlers/notification";
import { listSync_policys, listSync_policysStats, getSync_policy, createSync_policy, createSync_policyBulk, updateSync_policy, deleteSync_policy, deleteSync_policyRestore } from "./handlers/sync_policy";
import { listAudit_trails, listAudit_trailsStats, getAudit_trail, createAudit_trail, createAudit_trailBulk, updateAudit_trail } from "./handlers/audit_trail";

export const routes: Route[] = [
  { method: "POST", path: "/api/auth/signup", handler: limited(signup, "auth") },
  { method: "POST", path: "/api/auth/login", handler: limited(login, "auth") },
  { method: "POST", path: "/api/auth/logout", handler: limited(logout, "write") },
  { method: "GET", path: "/api/auth/me", handler: limited(me, "read") },
  { method: "GET", path: "/api/users", handler: limited(usersList, "read") },
  { method: "POST", path: "/api/users/invite", handler: limited(userInvite, "auth") },
  { method: "POST", path: "/api/users/:id/role", handler: limited(userSetRole, "write") },
  { method: "GET", path: "/api/audit", handler: limited(auditLog, "read") },
  { method: "GET", path: "/api/jobs", handler: limited(jobsList, "read") },
  { method: "POST", path: "/api/jobs/:id/cancel", handler: limited(jobCancel, "write") },
  { method: "POST", path: "/api/jobs/:id/requeue", handler: limited(jobRequeue, "write") },
  { method: "GET", path: "/api/search", handler: limited(search, "read") },
  { method: "POST", path: "/api/uploads", handler: limited(uploadCreate, "write") },
  { method: "GET", path: "/api/uploads", handler: limited(uploadList, "read") },
  { method: "GET", path: "/api/uploads/:id", handler: limited(uploadGet, "read") },
  { method: "DELETE", path: "/api/uploads/:id", handler: limited(uploadDelete, "write") },
  { method: "GET", path: "/api/sessions", handler: limited(sessionsList, "read") },
  { method: "DELETE", path: "/api/sessions/:id", handler: limited(revokeSession, "write") },
  { method: "GET", path: "/api/readings/stats", handler: limited(listReadingsStats, "read") },
  { method: "POST", path: "/api/readings/bulk", handler: limited(createReadingBulk, "write") },
  { method: "GET", path: "/api/sites/stats", handler: limited(listSitesStats, "read") },
  { method: "POST", path: "/api/sites/bulk", handler: limited(createSiteBulk, "write") },
  { method: "GET", path: "/api/sync_logs/stats", handler: limited(listSync_logsStats, "read") },
  { method: "POST", path: "/api/sync_logs/bulk", handler: limited(createSync_logBulk, "write") },
  { method: "GET", path: "/api/encryption_keys/stats", handler: limited(listEncryption_keysStats, "read") },
  { method: "POST", path: "/api/encryption_keys/bulk", handler: limited(createEncryption_keyBulk, "write") },
  { method: "GET", path: "/api/devices/stats", handler: limited(listDevicesStats, "read") },
  { method: "POST", path: "/api/devices/bulk", handler: limited(createDeviceBulk, "write") },
  { method: "GET", path: "/api/outliers/stats", handler: limited(listOutliers2Stats, "read") },
  { method: "POST", path: "/api/outliers/bulk", handler: limited(createOutlierBulk, "write") },
  { method: "GET", path: "/api/sync_thresholds/stats", handler: limited(listSync_thresholdsStats, "read") },
  { method: "POST", path: "/api/sync_thresholds/bulk", handler: limited(createSync_thresholdBulk, "write") },
  { method: "GET", path: "/api/passphrases/stats", handler: limited(listPassphrasesStats, "read") },
  { method: "POST", path: "/api/passphrases/bulk", handler: limited(createPassphraseBulk, "write") },
  { method: "GET", path: "/api/daily_aggregates/stats", handler: limited(listDaily_aggregatesStats, "read") },
  { method: "POST", path: "/api/daily_aggregates/bulk", handler: limited(createDaily_aggregateBulk, "write") },
  { method: "GET", path: "/api/connectivity_zones/stats", handler: limited(listConnectivity_zonesStats, "read") },
  { method: "POST", path: "/api/connectivity_zones/bulk", handler: limited(createConnectivity_zoneBulk, "write") },
  { method: "GET", path: "/api/reading_historys/stats", handler: limited(listReading_historysStats, "read") },
  { method: "POST", path: "/api/reading_historys/bulk", handler: limited(createReading_historyBulk, "write") },
  { method: "GET", path: "/api/site_visits/stats", handler: limited(listSite_visitsStats, "read") },
  { method: "POST", path: "/api/site_visits/bulk", handler: limited(createSite_visitBulk, "write") },
  { method: "GET", path: "/api/equipments/stats", handler: limited(listEquipmentsStats, "read") },
  { method: "POST", path: "/api/equipments/bulk", handler: limited(createEquipmentBulk, "write") },
  { method: "GET", path: "/api/calibration_logs/stats", handler: limited(listCalibration_logsStats, "read") },
  { method: "POST", path: "/api/calibration_logs/bulk", handler: limited(createCalibration_logBulk, "write") },
  { method: "GET", path: "/api/notifications/stats", handler: limited(listNotificationsStats, "read") },
  { method: "POST", path: "/api/notifications/bulk", handler: limited(createNotificationBulk, "write") },
  { method: "GET", path: "/api/sync_policys/stats", handler: limited(listSync_policysStats, "read") },
  { method: "POST", path: "/api/sync_policys/bulk", handler: limited(createSync_policyBulk, "write") },
  { method: "GET", path: "/api/audit_trails/stats", handler: limited(listAudit_trailsStats, "read") },
  { method: "POST", path: "/api/audit_trails/bulk", handler: limited(createAudit_trailBulk, "write") },
  { method: "GET", path: "/api/maintenance_schedules/stats", handler: limited(listMaintenance_schedulesStats, "read") },
  { method: "POST", path: "/api/maintenance_schedules/bulk", handler: limited(createMaintenance_scheduleBulk, "write") },
  { method: "GET", path: "/api/readings/outliers", handler: limited(listOutliers, "read") },
  { method: "GET", path: "/api/heatmap/sync-status", handler: limited(syncStatusHeatmap, "read") },
  { method: "GET", path: "/api/sites/:id/sync-stats", handler: limited(siteSyncStats, "read") },
  { method: "GET", path: "/api/daily-aggregates", handler: limited(dailyAggregates, "read") },
  { method: "GET", path: "/api/sites/:id/reading-trend", handler: limited(siteReadingTrend, "read") },
  { method: "GET", path: "/api/connectivity-zones/low-sync", handler: limited(lowSyncZones, "read") },
  { method: "GET", path: "/api/readings/pending-sync", handler: limited(pendingSyncReadings, "read") },
  { method: "GET", path: "/api/readings/failed-sync-threshold", handler: limited(failedSyncThresholdReadings, "read") },
  { method: "GET", path: "/api/sites/:id/equipment-status", handler: limited(siteEquipmentStatus, "read") },
  { method: "GET", path: "/api/outliers/unresolved", handler: limited(unresolvedOutliers, "read") },
  { method: "GET", path: "/api/visits/upcoming", handler: limited(upcomingVisits, "read") },
  { method: "GET", path: "/api/calibration/overdue", handler: limited(overdueCalibrations, "read") },
  { method: "GET", path: "/api/readings/dedupe-check", handler: limited(dedupeCheck, "read") },
  { method: "GET", path: "/api/devices/low-battery", handler: limited(lowBatteryDevices, "read") },
  { method: "GET", path: "/api/equipment/warranty-expiry", handler: limited(warrantyExpiry, "read") },
  { method: "GET", path: "/api/maintenance/overdue", handler: limited(overdueMaintenance, "read") },
  { method: "GET", path: "/api/readings", handler: limited(listReadings, "read") },
  { method: "GET", path: "/api/readings/:id", handler: limited(getReading, "read") },
  { method: "POST", path: "/api/readings", handler: limited(createReading, "write") },
  { method: "PATCH", path: "/api/readings/:id", handler: limited(updateReading, "write") },
  { method: "DELETE", path: "/api/readings/:id", handler: limited(deleteReading, "write") },
  { method: "POST", path: "/api/readings/:id/restore", handler: limited(deleteReadingRestore, "write") },
  { method: "GET", path: "/api/sites", handler: limited(listSites, "read") },
  { method: "GET", path: "/api/sites/:id", handler: limited(getSite, "read") },
  { method: "POST", path: "/api/sites", handler: limited(createSite, "write") },
  { method: "PATCH", path: "/api/sites/:id", handler: limited(updateSite, "write") },
  { method: "DELETE", path: "/api/sites/:id", handler: limited(deleteSite, "write") },
  { method: "POST", path: "/api/sites/:id/restore", handler: limited(deleteSiteRestore, "write") },
  { method: "GET", path: "/api/sync_logs", handler: limited(listSync_logs, "read") },
  { method: "GET", path: "/api/sync_logs/:id", handler: limited(getSync_log, "read") },
  { method: "POST", path: "/api/sync_logs", handler: limited(createSync_log, "write") },
  { method: "PATCH", path: "/api/sync_logs/:id", handler: limited(updateSync_log, "write") },
  { method: "GET", path: "/api/encryption_keys", handler: limited(listEncryption_keys, "read") },
  { method: "GET", path: "/api/encryption_keys/:id", handler: limited(getEncryption_key, "read") },
  { method: "POST", path: "/api/encryption_keys", handler: limited(createEncryption_key, "write") },
  { method: "PATCH", path: "/api/encryption_keys/:id", handler: limited(updateEncryption_key, "write") },
  { method: "DELETE", path: "/api/encryption_keys/:id", handler: limited(deleteEncryption_key, "write") },
  { method: "POST", path: "/api/encryption_keys/:id/restore", handler: limited(deleteEncryption_keyRestore, "write") },
  { method: "GET", path: "/api/devices", handler: limited(listDevices, "read") },
  { method: "GET", path: "/api/devices/:id", handler: limited(getDevice, "read") },
  { method: "POST", path: "/api/devices", handler: limited(createDevice, "write") },
  { method: "PATCH", path: "/api/devices/:id", handler: limited(updateDevice, "write") },
  { method: "DELETE", path: "/api/devices/:id", handler: limited(deleteDevice, "write") },
  { method: "POST", path: "/api/devices/:id/restore", handler: limited(deleteDeviceRestore, "write") },
  { method: "GET", path: "/api/outliers", handler: limited(listOutliers2, "read") },
  { method: "GET", path: "/api/outliers/:id", handler: limited(getOutlier, "read") },
  { method: "POST", path: "/api/outliers", handler: limited(createOutlier, "write") },
  { method: "PATCH", path: "/api/outliers/:id", handler: limited(updateOutlier, "write") },
  { method: "DELETE", path: "/api/outliers/:id", handler: limited(deleteOutlier, "write") },
  { method: "POST", path: "/api/outliers/:id/restore", handler: limited(deleteOutlierRestore, "write") },
  { method: "GET", path: "/api/sync_thresholds", handler: limited(listSync_thresholds, "read") },
  { method: "GET", path: "/api/sync_thresholds/:id", handler: limited(getSync_threshold, "read") },
  { method: "POST", path: "/api/sync_thresholds", handler: limited(createSync_threshold, "write") },
  { method: "PATCH", path: "/api/sync_thresholds/:id", handler: limited(updateSync_threshold, "write") },
  { method: "DELETE", path: "/api/sync_thresholds/:id", handler: limited(deleteSync_threshold, "write") },
  { method: "POST", path: "/api/sync_thresholds/:id/restore", handler: limited(deleteSync_thresholdRestore, "write") },
  { method: "GET", path: "/api/passphrases", handler: limited(listPassphrases, "read") },
  { method: "GET", path: "/api/passphrases/:id", handler: limited(getPassphrase, "read") },
  { method: "POST", path: "/api/passphrases", handler: limited(createPassphrase, "write") },
  { method: "PATCH", path: "/api/passphrases/:id", handler: limited(updatePassphrase, "write") },
  { method: "DELETE", path: "/api/passphrases/:id", handler: limited(deletePassphrase, "write") },
  { method: "POST", path: "/api/passphrases/:id/restore", handler: limited(deletePassphraseRestore, "write") },
  { method: "GET", path: "/api/daily_aggregates", handler: limited(listDaily_aggregates, "read") },
  { method: "GET", path: "/api/daily_aggregates/:id", handler: limited(getDaily_aggregate, "read") },
  { method: "POST", path: "/api/daily_aggregates", handler: limited(createDaily_aggregate, "write") },
  { method: "PATCH", path: "/api/daily_aggregates/:id", handler: limited(updateDaily_aggregate, "write") },
  { method: "DELETE", path: "/api/daily_aggregates/:id", handler: limited(deleteDaily_aggregate, "write") },
  { method: "POST", path: "/api/daily_aggregates/:id/restore", handler: limited(deleteDaily_aggregateRestore, "write") },
  { method: "GET", path: "/api/connectivity_zones", handler: limited(listConnectivity_zones, "read") },
  { method: "GET", path: "/api/connectivity_zones/:id", handler: limited(getConnectivity_zone, "read") },
  { method: "POST", path: "/api/connectivity_zones", handler: limited(createConnectivity_zone, "write") },
  { method: "PATCH", path: "/api/connectivity_zones/:id", handler: limited(updateConnectivity_zone, "write") },
  { method: "DELETE", path: "/api/connectivity_zones/:id", handler: limited(deleteConnectivity_zone, "write") },
  { method: "POST", path: "/api/connectivity_zones/:id/restore", handler: limited(deleteConnectivity_zoneRestore, "write") },
  { method: "GET", path: "/api/reading_historys", handler: limited(listReading_historys, "read") },
  { method: "GET", path: "/api/reading_historys/:id", handler: limited(getReading_history, "read") },
  { method: "POST", path: "/api/reading_historys", handler: limited(createReading_history, "write") },
  { method: "PATCH", path: "/api/reading_historys/:id", handler: limited(updateReading_history, "write") },
  { method: "GET", path: "/api/site_visits", handler: limited(listSite_visits, "read") },
  { method: "GET", path: "/api/site_visits/:id", handler: limited(getSite_visit, "read") },
  { method: "POST", path: "/api/site_visits", handler: limited(createSite_visit, "write") },
  { method: "PATCH", path: "/api/site_visits/:id", handler: limited(updateSite_visit, "write") },
  { method: "DELETE", path: "/api/site_visits/:id", handler: limited(deleteSite_visit, "write") },
  { method: "POST", path: "/api/site_visits/:id/restore", handler: limited(deleteSite_visitRestore, "write") },
  { method: "GET", path: "/api/equipments", handler: limited(listEquipments, "read") },
  { method: "GET", path: "/api/equipments/:id", handler: limited(getEquipment, "read") },
  { method: "POST", path: "/api/equipments", handler: limited(createEquipment, "write") },
  { method: "PATCH", path: "/api/equipments/:id", handler: limited(updateEquipment, "write") },
  { method: "DELETE", path: "/api/equipments/:id", handler: limited(deleteEquipment, "write") },
  { method: "POST", path: "/api/equipments/:id/restore", handler: limited(deleteEquipmentRestore, "write") },
  { method: "GET", path: "/api/calibration_logs", handler: limited(listCalibration_logs, "read") },
  { method: "GET", path: "/api/calibration_logs/:id", handler: limited(getCalibration_log, "read") },
  { method: "POST", path: "/api/calibration_logs", handler: limited(createCalibration_log, "write") },
  { method: "PATCH", path: "/api/calibration_logs/:id", handler: limited(updateCalibration_log, "write") },
  { method: "GET", path: "/api/notifications", handler: limited(listNotifications, "read") },
  { method: "GET", path: "/api/notifications/:id", handler: limited(getNotification, "read") },
  { method: "POST", path: "/api/notifications", handler: limited(createNotification, "write") },
  { method: "PATCH", path: "/api/notifications/:id", handler: limited(updateNotification, "write") },
  { method: "DELETE", path: "/api/notifications/:id", handler: limited(deleteNotification, "write") },
  { method: "POST", path: "/api/notifications/:id/restore", handler: limited(deleteNotificationRestore, "write") },
  { method: "GET", path: "/api/sync_policys", handler: limited(listSync_policys, "read") },
  { method: "GET", path: "/api/sync_policys/:id", handler: limited(getSync_policy, "read") },
  { method: "POST", path: "/api/sync_policys", handler: limited(createSync_policy, "write") },
  { method: "PATCH", path: "/api/sync_policys/:id", handler: limited(updateSync_policy, "write") },
  { method: "DELETE", path: "/api/sync_policys/:id", handler: limited(deleteSync_policy, "write") },
  { method: "POST", path: "/api/sync_policys/:id/restore", handler: limited(deleteSync_policyRestore, "write") },
  { method: "GET", path: "/api/audit_trails", handler: limited(listAudit_trails, "read") },
  { method: "GET", path: "/api/audit_trails/:id", handler: limited(getAudit_trail, "read") },
  { method: "POST", path: "/api/audit_trails", handler: limited(createAudit_trail, "write") },
  { method: "PATCH", path: "/api/audit_trails/:id", handler: limited(updateAudit_trail, "write") },
  { method: "GET", path: "/api/maintenance_schedules", handler: limited(listMaintenance_schedules, "read") },
  { method: "GET", path: "/api/maintenance_schedules/:id", handler: limited(getMaintenance_schedule, "read") },
  { method: "POST", path: "/api/maintenance_schedules", handler: limited(createMaintenance_schedule, "write") },
  { method: "PATCH", path: "/api/maintenance_schedules/:id", handler: limited(updateMaintenance_schedule, "write") },
  { method: "DELETE", path: "/api/maintenance_schedules/:id", handler: limited(deleteMaintenance_schedule, "write") },
  { method: "POST", path: "/api/maintenance_schedules/:id/restore", handler: limited(deleteMaintenance_scheduleRestore, "write") },
];
